sudo: false
language: cpp
compiler: g++

cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/../stateline-deps

addons: 
  apt: 
    sources: 
      - ubuntu-toolchain-r-test 
    packages: 
      - gcc-4.8 
      - g++-4.8
      - doxygen

# branch whitelist
branches:
  only:
    - test/travis-ci

before_install:
  - export STATELINE_SOURCE_DIR=$(pwd)
  - export PREREQ_DIR=${STATELINE_SOURCE_DIR}/../stateline-deps
  - ln -s /usr/bin/gcc-4.8 gcc
  - ln -s /usr/bin/g++-4.8 g++

install:
  - echo "nproc=$(nproc)"
  - g++ --version
  - ${STATELINE_SOURCE_DIR}/prereqs/travisPrereqs.sh ${STATELINE_SOURCE_DIR} ${PREREQ_DIR}
  - export BOOST_ROOT=$PREREQ_DIR
  - export Boost_INCLUDE_DIR=${PREREQ_DIR}/include/boost-1_55/
  - export BOOST_INCLUDEDIR=${PREREQ_DIR}/include/boost-1_55/

before_script:
  - cd ..
  - mkdir stateline-build
  - cd stateline-build

script:
  - cmake $STATELINE_SOURCE_DIR -DBoost_DEBUG=ON -DSTATELINE_BINARY_DIR=$(pwd) -DSTATELINE_SOURCE_DIR=$STATELINE_SOURCE_DIR -DPREREQ_DIR=$PREREQ_DIR $@
  - make
